import type {Metadata} from "next";
import {Inter, JetBrains_Mono, Sofia} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";

const interSans = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin"],
});

const sofia = Sofia({
    variable: "--font-sofia",
    style: "normal",
    weight: "400",
    subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${interSans.variable} ${sofia.variable} ${jetBrainsMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            {children}
        </ThemeProvider>
        </body>
        </html>
    );
}
